### ISSUE TITLE
Bug with reading Dinos pulled out with Ark tools

### ISSUE THREAD

**Issue by cyberangel67** [coldino/Larkator#13]
For the most part this program is great, however lately I started seeing inconsistencies with what the program says are on the map and what is actually on the map.

I have performed many saveworld's and even waited a few days, but it still reports or displays wrong information.

I have attached a screen shot of the generated data from Ark tools on the Quetz, yet this program says 90% of them do not exist on the map.

![capture](https://user-images.githubusercontent.com/1366816/36352649-398ebce4-1510-11e8-9002-2ff98c120876.PNG)

**Comment by coldino** [comment]
Did you miss that you've set Quetzal filter to female only? According to that json, Larkator should then only show the lvl 180 and lvl 100, which it appears to be doing correctly. Am I misreading this somehow?

**Comment by cyberangel67** [comment]
How do I set the filter to female only?

I have also seen it with every other Dino as well, it is almost like something is not working. For example there was supposed to be a level 300 Beaver at a certain location, yet I killed every beaver there and there was no level 300.

And I also did Dino Wipes and the information did not change either.

**Comment by coldino** [comment]
Mouse wheel over the pink female symbol next to Quetzal. It toggles between female, male and both. A number of the species in your screenshot show female-only filters.

**Comment by cyberangel67** [comment]
ok that explains it then. But to be honest that has got to be the stupidest way of filtering, because obviously I did it without knowing trying to scroll that section.

**Comment by coldino** [comment]
Yes, it clearly isn't a discoverable enough method but I haven't thought of a cleaner way yet.
I'll assume this solved your original issue.

**Comment by cyberangel67** [comment]
yeah it did thanks
