### ISSUE TITLE
REQ: Right Click Teleport Copy

### ISSUE THREAD

**Issue by Worldgate** [coldino/Larkator#14]
Would it be possible to add a right click in which you can copy the teleport command to goto that spot?  Be a lot easier to get to lost dinos if you can just hop over with a quick copy paste.

**Comment by coldino** [comment]
Nice idea. I'll add it to the todo list, but honestly I'm not sure when I will get to it.

**Comment by VIOrealm** [comment]
If you are playing Single Player, simply type the following...
tpcoords xx.x xx.x 0

xx = whatever the coordinates shown on Lark.

**Comment by coldino** [comment]
Better late than never!
