### ISSUE TITLE
Out of Memory 

### ISSUE THREAD

**Issue by maxlomb** [coldino/Larkator#16]
Hello,

I keep having the memory issues.
The files are loaded until a maximum size of about 90.000 Kb. More than that and get the outofmemory error.

I tried with the ini file and it does not work:

Initially because Win10 actually called the file ark-tools.l4j.ini.txt ....
I corrected than now to 
"ark-tools.l4j.ini"
now the error was:
"error: could not find or load main class Xmx4G"

I tried to put the  "-"  before the text Xmx4G. This time the error message was:
"Error could not creat the Jave Virtual Machine. Error: A fatal exception has occurred. Program will exit. Invalid maximum heap size: -Xmx4G The specified size exceeds the maximum representable size"

Any Ideas?

**Comment by Ghork19** [comment]
Hi,

I had the same problem as you, an out of memory when loading Wild Dinos and it did the same as you with the -Xmx4G thing. I did some research and I found how to solve that.
Follow this steps and you will be able to solve your problem too :

(For Windows 10)
First, go to Windows Settings, Apps, search for "Java 8 Update 171" or something like this and uninstall this.

Then go to this website: https://www.java.com/fr/download/manual.jsp and click on "Windows Offline (64 bits)" and download it.

Finally, when the download finished, just install this new java version and when it's done, launch Larkator, normally, it will work again.

**Comment by maxlomb** [comment]
Unfortunately did not help. I mean I did uninstall it. Went to the link, installed the Offline version and at the end seems like I installed the same thing... same Error after uninstall and reinstall two times.

**Comment by coldino** [comment]
Hi,

I believe the error you are seeing `Invalid maximum heap size: -Xmx4G` may mean you are running the 32-bit version of Java. It is unlikely that this will ever work with a large enough ark.

You should check you don't have multiple versions of Java installed, and ensure that the version you do have is 64-bit. If this doesn't help, please, report back.

**Comment by maxlomb** [comment]
Yes ...
I managed to get it working. Uninstalled everything, both JAVA version, Java 8 update 171 was installed and also some JAVA version 10... 

After that I installed the 64 bit version and finally Works!!!!

Great Tool the LARKATOR.
Is there a version also for the other maps? 
Does it work also on PVE oder PVP?

Thank you
Max

**Comment by coldino** [comment]
Hopefully not an issue now ark-tools is no longer required.
