### ISSUE TITLE
Add an other map (iso crystal  isles)

### ISSUE THREAD

**Issue by LotekHeavy** [coldino/Larkator#17]
Is there a way to add another map? Like his one:

- Mod/Map:  https://steamcommunity.com/sharedfiles/filedetails/?id=804312798
- Map Images: https://ark.heavy.ch/sites/default/files/karte/2018-04/IsoCrystalIsles_MiniMap_SMALL.jpg

**Comment by coldino** [comment]
This is possible, but the coordinate system transforms are also needed.

If a transform can't be found, I've worked out a way to calibrate based on ingame items. It would require flying/teleporting round the bounds of the map, placing storage boxes and naming them with a specific tag and the GPs lat/lon. If you are willing to do this and provide the savegame, I can add the map.
