### ISSUE TITLE
Backup & Restore Option

### ISSUE THREAD

**Issue by VIOrealm** [coldino/Larkator#21]
I've been using this for a while and every now and then it flips out and all the settings get lost.  I then have to add all the dinos again.  Perhaps a simple backup & restore option in the Settings section?  At least people would only need to edit the sex or level settings rather than adding all or many of the dinos again.

**Comment by VIOrealm** [comment]
Again my settings (M/F & Level) got lost.  I tried backing up the folders labeled tamed and wild.  I restored those but it didn't take the (M/F & Level) settings.  Could you tell me how to manually backup those settings?

**Comment by VIOrealm** [comment]
I found where it keeps these settings and have created a little batch file to copy/backup the file.  The information is stored in a file called user.config at the following location.   It may vary from person to person but so search for it if it is not there. 
 C:\Users\----YOUR NAME----\AppData\Local\Apps\2.0\Data\VAHD0KLJ.V4H\YD63ONVQ.DLB\lark..tion_0000000000000000_0001.0007_9eb2b93bba0ca523\Data\1.0.0.0\user.config 
****Replace ----YOUR NAME--- with your Windows user account.

**Comment by coldino** [comment]
Very sorry about the settings. That is a pain, but you've found the right file.

Have you any idea what triggers the settings to be lost?

**Comment by VIOrealm** [comment]
It's happened to me when I'm switching between Tamed and The Hunt.  Not always.  Also, when I accidently opened a second application of Lark (had 2 running).  Might add code check to see if already running to simply expand/open.

**Comment by coldino** [comment]
The bug was found and resolved. It happened sometimes when settings were saved while the tames were being shown.

I won't restrict Larkator to be single-instance as it some people use it for multiple maps at the same time.

**Comment by b-morgan** [comment]
There must be a better "location" for the user.config file.

**Comment by coldino** [comment]
This is not under my control. It's part of Microsoft's installer system.
