### ISSUE TITLE
Recent Changes

### ISSUE THREAD

**Issue by VIOrealm** [coldino/Larkator#24]
I noticed that some updates were made recently.  Did you eliminate the "classes.json" file?

**Comment by coldino** [comment]
Yes. ark-tools, which generated `classes.json` and all of the temporary output is eliminated entirely from the process. This has resulted in tremendous speedups, much simpler code, and the possibility to access much more information from the save file.

Sadly, I see for you it has removed the opportunity to work around modded species names appearing badly. I will think about a solution for this - perhaps allowing you to supply a custom JSON file.

Feel free to find me in [ArkSmartBreeding's](https://github.com/cadon/ARKStatsExtractor) Discord.
