### ISSUE TITLE
Add creature unique id to list - enhancement

### ISSUE THREAD

**Issue by Jaskari161** [coldino/Larkator#25]
Is there a way to add the unique dino id to the list of tamed dinos when displayed? I am using this tool to look for duped dinos and the duplicated dinos appear to have the same dino id.

**Comment by coldino** [comment]
That's a bit outside what Larkator was designed to do.

You could either use ark-tools and look in the generated JSON files, or take a look at [a new tool](https://github.com/Flachdachs/ArkSaveAnalyzer) from Flachdachs that lets you rummage through the save file.
