### ISSUE TITLE
How to set Sex, Min, Max

### ISSUE THREAD

**Issue by b-morgan** [coldino/Larkator#26]
When I first start the program, "The Hunt" shows "Worries" and "Shopping List" pre-loaded with some values: Name, Sex, Min, Max, and a X to delete. At the bottom, there is a + to add.

1. Is it possible to "edit" existing entries?
2. When I click the + to add I have a choice of which list and name. Min and Max are shown but I can't figure out how to add/edit them. Is this possible?
3. If there is any additional documentation or a better place to ask questions, please add it to the Wiki.

**Comment by coldino** [comment]
From the main page: "Use your mouse's scroll wheel over a search filter's gender and level selector to change them".

I realise this isn't the most intuitive method to find, but it's very convenient once learnt, and keeps the UI nice and minimal.
