### ISSUE TITLE
Found unknown Version 8827

### ISSUE THREAD

**Issue by Wulf2k** [coldino/Larkator#27]
Got my save (TheIsland.ark) off my Nitrado server and the tool gives that error.

Any update on the horizon, or is it an issue with it being an Xbox One save?

**Comment by coldino** [comment]
Oh dear - I don't know if that's an issue with an Ark update or the switch to SavegameToolkit causing a problem with Xbox saves.

Was it working with your Xbox save previously or is this a first attempt?

**Comment by Wulf2k** [comment]
This was a first attempt, so I have no access to any pre-update copies of the save to test.

**Comment by Wulf2k** [comment]
After the hex edit, it successfully finds all the tames, but only lists about 15 wild creatures.  Is that expected behaviour?  Does it not actually not creatures outside of render?

Or an indication that more than just the version changed?

**Comment by coldino** [comment]
Sorry for the delay.

The lack of wild creatures in the save is a serious worry. Normally, creatures that leave render range go into hibernation, and are saved in a hibernation area within the save file. This is read correctly on the PC version.

Savegametoolkit (by Flachdachs) is an almost exact translation of the abandoned ark-tools (by Qowyn) to C#. Adding support for changes to the file format may require more expertise than we collectively have. I'll speak with Flachdachs and see if there's anything we can do.

**Comment by Wulf2k** [comment]
After using it a bit  more with multiple copies of the save, I can report that the tool "mostly" works.  I've seen some weirdness with creatures I know exist not appearing, and ones it reports not being there when I go in-game, but nothing I've properly documented and can't rule out user error completely.

Smart Breeder has definitely had some issues with some sections of the data though, so if they're both using the same framework I'd expect that neither is doing a perfect job.

If you could allow it to open v10 files as-is (possibly with a warning) it would probably be close enough for most people's purposes.

**Comment by coldino** [comment]
As much as I'd like to support the format, I'm not happy with partial support like this. I would fully expect complaints about creatures not being found, but there would also be a strong chance of exceptions during the loading process.

If we get better support from the savegametoolkit I will of course update.

For you personally I would recommend compiling a custom savegametoolkit DLL with a different version check.
