### ISSUE TITLE
adding new dinos?

### ISSUE THREAD

**Issue by XavierGray** [coldino/Larkator#29]
HI Coldino.   Love the larkator, so helpful on my single player game. Thanks so much for taking the time to make this. This is the only dino locator i know of that doesn't require you to "prevent hibernation" to work.

i was wondering if you will be doing any updates to add some of the new dinos.
IE, alpha tuso, gachas, wyverns, rock drakes, etc.

Thanks again

**Comment by coldino** [comment]
Thank you!

Larkator should already support everything supported by Ark, and it'll even have a go at listing modded creatures (just without nice names).

The catch is that the species **_must exist on your map_** before Larkator can see it and list it!

**Comment by Flachdachs** [comment]
Additional info: hibernation prevents that mods can see more than the loaded areas, because hibernated areas are inaccessible for the normal game mechanics. So no mod is able to find all creatures if hibernation is not prevented. Larkator can find them all, because it reads the save file. To save the whole map the current area as well as the hibernated parts have to be written into the file, so a save file reader can read all.

**Comment by XavierGray** [comment]
Ok. thanks for the reply. Is 1.9.2.1 the latest build?
I was just confused because on the island and rag, alpha tuso isn't even in the list as an option.
And when i first loaded up the extinction map, I didn't see gachas in the list. But, now i just loaded into rag, and i can see wyverns in the list. So, it must just be me being an idiot. Thanks for taking the time to reply though, i really appreciate it.

Thanks for the explanation Flachdachs. Exactly the reason i love larkator. preventing hibernation can really slow down your game due to the shear amount of information the game will then require trying to process all the "out of render" areas.

**Comment by Flachdachs** [comment]
Things out of render area are "in stasis" if you prevent hibernation. So in neither case are they processed. The only difference I can see is a freeze when the game is saving and has to consider all creatures. In hibernation mode it doesn't freeze. Then the creatures apparently need to be just written without a noticeable processing time.
