### ISSUE TITLE
Hiding cave dinos (checkbox?)

### ISSUE THREAD

**Issue by ToeiRei** [coldino/Larkator#30]
Cave dinos could be marked as untameable. However - that flag might be useful here

**Comment by Flachdachs** [comment]
Untameable specimen of tameable species have a boolean property bForceDisablingTaming set to true. "Cave" is not a criterion. So, untameable creatures can be filtered easily when considering the mentioned property.

**Comment by coldino** [comment]
This feature has been merged and should be released soon.
