### ISSUE TITLE
Ragnarok map misaligned

### ISSUE THREAD

**Issue by sas8jedi** [coldino/Larkator#35]
The dino marks of certain coordinates point to the wrong locations on the Ragnarok map.
![Larkator001](https://user-images.githubusercontent.com/13964590/59603824-1a1c9e00-9113-11e9-861c-ba4d6da72d19.png)

**Comment by coldino** [comment]
Sadly these images have their grid lines in the wrong place so I don't align with those. It's very confusing :(

I've tried to align the pin locations with the drawing of the landmasses instead, so they should look like they are in the right place relative to landscape features.

That said, they could easily need tweaking.

**Comment by coldino** [comment]
Next release will have significantly tweaked Ragnarok values based on a new calibration system.

The positions of ~150 storage crates placed around the coastline are matched up to the map image, completely ignoring the grid. Note that on Rag in particular some of the map image is out of date and simply wrong.

![image](https://user-images.githubusercontent.com/28345893/112773301-63f71f80-902d-11eb-8497-b6c7335eac15.png)
