### ISSUE TITLE
Add Valguero

### ISSUE THREAD

**Issue by Rottenbeer** [coldino/Larkator#38]
Hi!
I try to add the Valguero map, but I can't figure out which values I need in the calibrations.json file.
How to use the calibrator?

**Comment by LotekHeavy** [comment]
Yes, I would need it, too. How?

**Comment by eddielane71488** [comment]
I am not good with coding, but anything you would need in-game, I would be willing to offer if you were willing to expand to the current maps @coldino

**Comment by coldino** [comment]
Thanks for your contribution @Rottenbeer! This is now merged and released in v1.10.

@eddielane71488 I wish I had seen your message earlier - I just spent 4 days placing over 1000 storage boxes (renamed with their Lat/Lon) around the coast line of each and every WC map!
