### ISSUE TITLE
Can't Uninstall or Move After Install

### ISSUE THREAD

**Issue by Worldgate** [coldino/Larkator#4]
Trying to get this working, had to remove the files and then put it in another location and now it complains it already has it installed elsewhere.  Tried removing all the keys from the registry but no luck still.

**Comment by coldino** [comment]
Interesting. This is just a standard ClickOnce installer.

According to [this thread on SO](https://stackoverflow.com/questions/10896223/how-do-i-completely-uninstall-a-clickonce-application-from-my-computer) there's a couple of things you can try. As you've removed most of it, you may just be able to clean the cache: `rundll32 dfshim CleanOnlineAppCache`

I notice you also posted a further issue on the forum thread. Could you post the exact paths you are using for both ark-tools and your ARK file in a new issue? Thanks for trying the tool and I hope we can get this ironed out.

**Comment by Worldgate** [comment]
I ended up wiping that computer out because of some ark issues so i cant replicate it.
