### ISSUE TITLE
compiling instructions ?

### ISSUE THREAD

**Issue by sixokig** [coldino/Larkator#41]
I have created my own fork and merged the 3 pull requests to it, I downloaded the code but I find zero instruction to compile it :(

Can someone help please, I'm not a dev

**Comment by coldino** [comment]
For future reference... it's just a case of loading into Visual Studio and asking it to build <3

1) Install Visual Studio 2019 Community Edition
1) Download the project files, or if cloning using Git *remember to include sub-modules*
1) Open the solution `Larkator.sln` in Visual Studio
1) Right-click the `LarkatorGUI` project and select "Set as Startup Project"

From this point you can start Larkator with debugging using `F5` (or *Debug -> Start Debugging* menu)...

...or change build configuration from "Debug" to "Release" (in the toolbar) and `Ctrl-Shift-B` (or *Build -> Build Solution*) to build ready for sharing. You'll find the output in `LarkatorGUI\bin\Release`.
