### ISSUE TITLE
Out of memory was thrown error (Epic Store version)

### ISSUE THREAD

**Issue by nedfred123** [coldino/Larkator#47]
The tool worked until yesterday.My save size is 51 kb.The game works perfectly,with and without the tool launched.I play on epic store.If you need any more info ask,the tool is great and i would really like to continue using it. I tried reinstalled  the tool 3 times to try and fix the tool,but so far no use.
![Esker](https://user-images.githubusercontent.com/67920657/86620441-9acb6800-bfbc-11ea-9160-d28cd71f38ca.png)

**Comment by coldino** [comment]
This is a shame as it indicates Wildcard changed the savegame format for the Epic store.

Larkator uses [Flachdachs/ArkSavegameToolkit](https://github.com/Flachdachs/ArkSavegameToolkit) to read the save files, which was a port of the much older Java [ark-tools](https://github.com/Qowyn/ark-tools). Neither are being updated currently and I don't have the knowledge to make the modifications myself, so I don't see Epic-version savegames being supported in the near future.

**Comment by coldino** [comment]
I'd like a copy of an Epic save file to begin investigating this.

**Comment by nedfred123** [comment]
Unfortunately i deleted the game and its files :/

**Comment by bradpoulton** [comment]
@coldino Are you still in need of an Epic games file? I have an unofficial multiplayer server and i can provide a .ark saved game file.

**Comment by coldino** [comment]
@bradpoulton  Thanks! If the save file is causing an error then absolutely, yes. It's also nice to know if it works without error, but I don't think I need a copy.

**Comment by bradpoulton** [comment]
Ok, I was able to use it without errors. I downloaded my .ark file via FTP and loaded it in Larkator.  When I first loaded up the file, my computer froze up for a couple of minutes. I was patient and the file finally loaded up. The file size is 33.1 MB (34,806,931 bytes). Thanks for making this software! Very helpful!
