### ISSUE TITLE
wrong language or format settings

### ISSUE THREAD

**Issue by bergemannmartin** [coldino/Larkator#48]
Hi, 

nice project you got there. I just downloaded to locate my lost rex and IT WORKED, thanks for that!

BUT: Trying to use the obviously new feature to copy the teleport command, I get this:
"cheat SetPlayerPos -119371,91 226859,97 -12727,97 | cheat fly"

notice the "," instead of "." as decimal separator. I did not test yet (which I should) if the program uses my country settings (German, btw) or if the program is compiled that way.

Regards

**Comment by coldino** [comment]
@WiredSharp was kind enough to provide a fix for this in #40. It has been merged and should be released soon.
