### ISSUE TITLE
Fire is the only Wyvern tame I can see on Ragnarok

### ISSUE THREAD

**Issue by Aoxo** [coldino/Larkator#49]
I was trying to locate a friends Lightning Wyvern tame on Ragnarok, but only Fire Wyvern is listed.  I'm flying on a Lightning Wyvern right now on the map.

P.S.  Thank you great program!

**Comment by coldino** [comment]
Might be the same issue as #51. Maybe Ark has changed how hibernation works.

If someone can supply a save file that shows the problem so I can analyse it that would help a lot.

**Comment by coldino** [comment]
Closing in favour of #51.
