### ISSUE TITLE
Willing to pay for an update.

### ISSUE THREAD

**Issue by Magyar5** [coldino/Larkator#50]
I have worked as a coder before and understand the time and resources necessary to create and maintain these types of things.  I would be willing to pay for an updated version of Larkator to include all the official maps and Genesis part 2 when it releases next year.  I am sure others who find your tool valuable would be willing to contribute for your efforts.  Please let me know what I can do to entice you to update this wonderful and useful tool.

**Comment by jinxwad** [comment]
I also would be willing to contribute financially to this project.

**Comment by coldino** [comment]
I see this. Thank you for the interest.

There are plenty of reasons to restart the project so I'm going to spend some time considering the options, which might include a re-write to make continued development easier.

Financial support is certainly welcome and I'll look at setting that up.  I feel I'd like to get some progress towards an update before that, however.

**Comment by Magyar5** [comment]
That's understandable.  I've recently retired from the IT industry and few
realize the time and effort necessary to create such innovative and robust
solutions.  You deserve to be compensated for your efforts.

Jacob Johnson
706-662-6000
