### ISSUE TITLE
Not Showing Tames

### ISSUE THREAD

**Issue by ZephyrZymbol** [coldino/Larkator#51]
Figured out how to track wild dinos, but it doesn't even list my tames when I click "Show Tames". Did I do sth wrong? I followed the instructions on the wiki...
![Larkator](https://user-images.githubusercontent.com/77612481/104895579-6b5cd580-59b9-11eb-982d-c1cdbed89837.JPG)

**Comment by coldino** [comment]
I'm not sure how this happened. Maybe you could upload your .ark somewhere so I can try to reproduce it?

The status bar showing 109 wild creatures and 0 tames found is worrying. Maybe you pointed to the wrong save file?

**Comment by ZephyrZymbol** [comment]
I only have the one .ark, so not likely pointing out the wrong one. Any
suggestions on an upload loca?

**Comment by coldino** [comment]
Maybe Dropbox or Google Drive? Anything you can generate a public link for.

**Comment by ZephyrZymbol** [comment]
Ok, I have uploaded my .ark to my Google Drive at the following Link

https://drive.google.com/file/d/1dL48AQwDO6GKsbsaz5yA-m_cTcdms8eN/view?usp=sharing

**Comment by coldino** [comment]
Thanks. Now 1.10 is published with the new maps I'll take a look into this.

**Comment by ZephyrZymbol** [comment]
Sounds good to me, thanks for the update. Was starting to wonder if you had
forgotten about me, but figured it was something to do with a possible
update to your project.

**Comment by coldino** [comment]
Initial investigation shows I can't find a single creature that looks tamed in that save file, even looking much deeper than Larkator usually does.

Any chance you can contact me on Discord to supply some more information and answer some questions? You'll find me as coldino#7792 or on ASB's server (https://discord.gg/qCYYbQK).

**Comment by ZephyrZymbol** [comment]
Not sure if we're in similar time zones; I'm in Japan. I haven't modded Ark
at all, and I was playing with my son, acting as a server for the two of
us. I don't have Discord, but if you insist, I will join.

**Comment by coldino** [comment]
Okay well assuming you don't get on Discord... my theory is that you've loaded your *local* save file instead of the save file from the server. The save file you sent has no tames in it and appears to only be a few minutes old. 

Clients connected to a server don't get a copy of the save game - you need to fetch it from the server manually.

Going to close this issue under that assumption, but feel free to get back to me if you still have trouble.

**Comment by ZephyrZymbol** [comment]
My local save IS the server save. I don't play on a server, I acted as
server for myself and my son.
