### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by xibalbus** [coldino/Larkator#64]
Hi,

I tried to install tonight and got the following:

`The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.7 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 528372
Setting value '528372 {int}' for property 'DotNet47Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet47Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.7 (x86 and x64)':
Property: [DotNet47Full_OSIntegrated] = 1 {int}
Property: [DotNet47Full_Release] = 528372 {int}
Running checks for command 'DotNetFX47\NDP47-KB3186497-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX47\NDP47-KB3186497-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX47\NDP47-KB3186500-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet47Full_Release' and value '460798': true
Result of checks for command 'DotNetFX47\NDP47-KB3186500-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.7 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://raw.githubusercontent.com/coldino/Larkator-release/master/publish/LarkatorGUI.application'.
`

**Comment by coldino** [comment]
It looks like your system is blocking the installer's access to the install files. You might need to allow it through your virus/malware detector.

In particular it is failing to reach [this link](https://raw.githubusercontent.com/coldino/Larkator-release/master/publish/LarkatorGUI.application), but this is just the first of the files it needs.

**Comment by coldino** [comment]
Given we had a couple of reports of this error recently I've updated the installer and its required .Net Framework to v4.8.

Try installing the latest release using (setup.exe)[https://github.com/coldino/Larkator-release/raw/master/publish/setup.exe], and if that doesn't work see if you can use the (LarkatorGUI.application)[https://github.com/coldino/Larkator-release/raw/master/publish/LarkatorGUI.application] file directly.
