### ISSUE TITLE
Administrator Blocked

### ISSUE THREAD

**Issue by admiralTANK** [coldino/Larkator#66]
I followed some of the guides and instructions, but my Windows 10 says the Administrator has blocked the app. I am of course the Administrator or so I thought. My account says owner.

Below "Windows protected your PC" more info reveals the "Run anyway button.
![image](https://user-images.githubusercontent.com/82894877/153735863-85f085ab-0861-4fea-b83f-3f64d52bc913.png)

This pops up briefly
![image](https://user-images.githubusercontent.com/82894877/153735893-4a05295a-99f1-4dae-b1a5-ace1b03f52e9.png)

Finally, I hit a dead-end when this page pops up. I can find no buttons beside the X and Close
![image](https://user-images.githubusercontent.com/82894877/153735913-74f62c6d-bbc9-478c-b624-710b712d70e5.png)

I followed this installation guide as far as I could, but there seems to be a discrepancy at step 3
https://github.com/coldino/Larkator/wiki/Installation

**Comment by coldino** [comment]
Hmmm. Searching around I see registry changes that would cause/fix this, but I'd love to know what it is about your system that caused this in the first place.

In Windows 10 there's a setting to disable installing software from anywhere but the Windows Store. Maybe you have that set? Let me know if you can't find it.
