### ISSUE TITLE
Alpha Ember - and Alpha Blood - and Alpha Tropical Wyvern

### ISSUE THREAD

**Issue by kkm** [coldino/Larkator#69]
I cant find this in drop downlist.

**Comment by coldino** [comment]
I guess these are from a mod? If so they'll appear with their internal class name (something that looks a bit like `CrystalWyvern_Character_BP_WS`. There's no way to extract proper species names from the save file and it would be a never-ending huge task to try to gather species names from all the mods people play.

But it's also possible that there are simply none of that species currently spawned - only species are that currently spawned on the map can be listed.
