### ISSUE TITLE
Don't savegame while in "tamed" section

### ISSUE THREAD

**Issue by lightningbug9** [coldino/Larkator#7]
If you are in the tamed section of the locator, and saveworld ingame, it will refresh larkator and delete the current stuff in "the hunt". It will allow you to find new dinos, but the shopping list and the worries sections are totally deleted, with the dropdown showing up blank and no header on the dino list. It basically looks and acts like your tamed list, with the ability to find dinos not tamed. The only way I found to restore was to go to settings and reset to defaults. This also happens when the game automatically saves or Larkator refreshes. It has happened to me again at a random moment, and right now I'm continuing to use it this way since I don't want to lose my saved hunts. It's still extremely useful to find dinos, but the map is a little off. (my base is on the beach and all of my dinos show up in the ocean. I've figured out that it's always a few centimeters off diagonally to the top right corner)

**Comment by coldino** [comment]
This doesn't happen for me. It could be that your game take a little longer to save than mine and so the conversion fails, perhaps clearing the list of available species - which might have the effect of deleting your hunt list.

Currently there's a fixed 2 second wait between detecting the ark has changed and converting it. I'll add a configuration option so you can try upping that. 

I should probably also put in protection against finding a failed ark conversion.

**Comment by coldino** [comment]
I've published a new version v1.5 (6c8c289) with some added resilience and new delay setting (22ff9f5, 8da8bda). Try upping this to 5000ms if necessary to test it, then if it works bring it down as far as you can. Keep an eye on any messages in the status bar immediately after saving your game and let me know what happens.

I'll make a new issue for the map offset.

**Comment by coldino** [comment]
Assuming this is sorted with the changes I made. Let me know if not.
