### ISSUE TITLE
Error: Capacity was less than current size

### ISSUE THREAD

**Issue by KumaDeBeer** [coldino/Larkator#83]
I've been playing on a Nitrado server I bought(rent?). I download the save file via a FTP on a daily base. Since this morning I have been getting the following error: Capacity was less than current size. Parameter name: value. This doesn't happen with Single Player save files.
The save file from the server is 45,975 KB while the one from single player is 53,769 KB. I also reboot the server to update the save file, but that didn't yield any differences.

Map I'm playing on is The Island.

![image](https://user-images.githubusercontent.com/112780678/188286484-f3c368ad-5688-41c1-9b04-e96226ee7807.png)

**Comment by xradius17** [comment]
I "think" this is an issue with the PAX event happening in ark currently. Larkator still works on saves that do not have any PAX colored dinos, wild or tamed in the save file.  Once you tame a dino from the event or have any wild dinos from the event, Lakator throws the error you posted.  Hopes this helps the devs resolve the issue.

**Comment by KumaDeBeer** [comment]
> I "think" this is an issue with the PAX event happening in ark currently. Larkator still works on saves that do not have any PAX colored dinos, wild or tamed in the save file. Once you tame a dino from the event or have any wild dinos from the event, Lakator throws the error you posted. Hopes this helps the devs resolve the issue.

I'll try to turn the event off, wipe wild dinosaurs and restart the server in a couple minutes, will update if that helps

**Comment by xradius17** [comment]
Make sure you don't have any tames from the event either.

**Comment by xradius17** [comment]
Looks like it is the PAX update itself. server version 349.10.  It is happening for me on multiple maps.  Fordur, Lost Island, and Crystal Isles.

**Comment by KumaDeBeer** [comment]
> Looks like it is the PAX update itself. server version 349.10. It is happening for me on multiple maps. Fordur, Lost Island, and Crystal Isles.

I killed all tames from the last 24 hours, luckily it werent that many. The error still persists, so might be the patch itself yeah

**Comment by Onatel** [comment]
Hi there, good to see I´m not the only one with this error. I´ve the same on my dedicated ARK-Server, on the Fjordur-Map.

**Comment by coldino** [comment]
Yup, there has been a mysterious format change in the save file. Currently only affects the server builds, and unfortunately does **not** come with a change to the version field in the files.

Thanks to @alex4401 and @cadon the SavegameToolkit now has a quick workaround in place. I'll put a release of Larkator out today containing it.

That said, Wildcard themselves don't seem to be aware of the change or the difference between client and server saves right now. Hopefully we can clear some of this up in future.

**Comment by coldino** [comment]
v1.18 is released with this fix (5ec6f0d87508b4b162533bdcae1c676a4875aba2). Seems to work for both old and new, client and server.

Feels like this is something that might need to evolve over time, so let me know if you see more problems.

**Comment by xradius17** [comment]
Thank you!

**Comment by KumaDeBeer** [comment]
> v1.18 is released with this fix ([5ec6f0d](https://github.com/coldino/Larkator/commit/5ec6f0d87508b4b162533bdcae1c676a4875aba2)). Seems to work for both old and new, client and server.
> 
> Feels like this is something that might need to evolve over time, so let me know if you see more problems.

Great, thanks for the effort and quick fix!

**Comment by Onatel** [comment]
Thx a lot for the quick fix.
